spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasklib?useSSL=false&serverTimezone=Europe/Moscow

    username: root
    password: Test1234
  jpa:
    hibernate:
      ddl-auto: create

someParameter:
  value: 5463